// <auto-generated />
using System;
using DJERICMAX_App.Repositorio.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DJERICMAX_App.Repositorio.Migrations
{
    [DbContext(typeof(DJERICMAX_AppContexto))]
    [Migration("20250626211922_SegundaVersaoBase")]
    partial class SegundaVersaoBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DJERICMAX_App.Dominio.Entidades.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("PedidoId");

                    b.Property<int>("Quantidade_Horas")
                        .HasMaxLength(2);

                    b.Property<int>("ServicoId")
                        .HasMaxLength(9);

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("ItemPedidos");
                });

            modelBuilder.Entity("DJERICMAX_App.Dominio.Entidades.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CEP_Evento")
                        .HasMaxLength(10);

                    b.Property<string>("CEP_Usuario")
                        .HasMaxLength(10);

                    b.Property<string>("Cidade_Evento")
                        .HasMaxLength(100);

                    b.Property<string>("Cidade_Usuario")
                        .HasMaxLength(100);

                    b.Property<DateTime>("Data_Cadastro");

                    b.Property<DateTime>("Data_Contrato");

                    b.Property<DateTime>("Data_Evento");

                    b.Property<int>("FormaPagamentoId");

                    b.Property<string>("Logradouro_Evento")
                        .HasMaxLength(200);

                    b.Property<string>("Logradouro_Usuario")
                        .HasMaxLength(200);

                    b.Property<int>("NumeroLogradouro_Evento")
                        .HasMaxLength(10);

                    b.Property<int>("NumeroLogradouro_Usuario")
                        .HasMaxLength(10);

                    b.Property<bool>("Parcelado");

                    b.Property<int>("Qtde_Parcelas");

                    b.Property<string>("UF_Evento")
                        .HasMaxLength(2);

                    b.Property<string>("UF_Usuario")
                        .HasMaxLength(2);

                    b.Property<int>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("FormaPagamentoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("DJERICMAX_App.Dominio.Entidades.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<decimal>("Preco_Hora");

                    b.HasKey("Id");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("DJERICMAX_App.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.Property<string>("SobreNome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("DJERICMAX_App.Dominio.ObjetoDeValor.FormaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao")
                        .HasMaxLength(500);

                    b.Property<string>("Nome")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("FormaPagamento");
                });

            modelBuilder.Entity("DJERICMAX_App.Dominio.Entidades.ItemPedido", b =>
                {
                    b.HasOne("DJERICMAX_App.Dominio.Entidades.Pedido")
                        .WithMany("ItensPedido")
                        .HasForeignKey("PedidoId");
                });

            modelBuilder.Entity("DJERICMAX_App.Dominio.Entidades.Pedido", b =>
                {
                    b.HasOne("DJERICMAX_App.Dominio.ObjetoDeValor.FormaPagamento", "FormaPagamento")
                        .WithMany()
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DJERICMAX_App.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
