// <auto-generated />
using System;
using DJERICMAX_App.Repositorio.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DJERICMAX_App.Repositorio.Migrations
{
    [DbContext(typeof(DJERICMAX_AppContexto))]
    partial class DJERICMAX_AppContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DJERICMAX_App.Dominio.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro")
                        .HasMaxLength(50);

                    b.Property<string>("CEP")
                        .HasMaxLength(9);

                    b.Property<string>("CPF")
                        .HasMaxLength(14);

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("Data_Cadastro");

                    b.Property<int>("EhCliente");

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<string>("Logradouro")
                        .HasMaxLength(50);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Num_Logradouro")
                        .HasMaxLength(5);

                    b.Property<string>("RG")
                        .HasMaxLength(12);

                    b.Property<string>("SobreNome")
                        .HasMaxLength(50);

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(13);

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("DJERICMAX_App.Dominio.Entidades.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BairroEvento")
                        .HasMaxLength(30);

                    b.Property<string>("CepEvento")
                        .HasMaxLength(9);

                    b.Property<string>("CidadeEvento")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int>("ClienteId");

                    b.Property<int>("Convidados")
                        .HasMaxLength(3);

                    b.Property<DateTime>("DataCadastro");

                    b.Property<DateTime>("DataContrato");

                    b.Property<DateTime>("DataEvento");

                    b.Property<bool>("Fechado");

                    b.Property<int>("FormaPagamentoId");

                    b.Property<DateTime>("HoraFinal");

                    b.Property<DateTime>("HoraInicio");

                    b.Property<string>("LogradouroEvento")
                        .HasMaxLength(50);

                    b.Property<string>("NomeEvento")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("NumLogradouroEvento")
                        .HasMaxLength(5);

                    b.Property<string>("Observacoes")
                        .HasMaxLength(600);

                    b.Property<string>("Pacote")
                        .HasMaxLength(50);

                    b.Property<bool>("Parcelado");

                    b.Property<bool>("Proposta");

                    b.Property<int>("QtdeParcelas")
                        .HasMaxLength(2);

                    b.Property<bool>("Realizado");

                    b.Property<string>("UfEvento")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<int>("ValorParcelas")
                        .HasMaxLength(5);

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FormaPagamentoId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("DJERICMAX_App.Dominio.Entidades.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EventoId");

                    b.Property<int?>("PedidoId");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("Quantidade_Horas");

                    b.Property<int>("ServicoId");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ServicoId");

                    b.ToTable("ItemPedidos");
                });

            modelBuilder.Entity("DJERICMAX_App.Dominio.Entidades.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClienteId");

                    b.Property<DateTime>("DataPedido");

                    b.Property<int>("FormaPagamentoId");

                    b.Property<int?>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FormaPagamentoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("DJERICMAX_App.Dominio.Entidades.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("NomeArquivo")
                        .HasMaxLength(255);

                    b.Property<decimal>("Preco_Hora")
                        .HasColumnType("decimal(19,4)");

                    b.HasKey("Id");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("DJERICMAX_App.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14);

                    b.Property<bool>("EhAdministrador");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("NomeArquivo");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.Property<string>("SobreNome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("DJERICMAX_App.Dominio.ObjetoDeValor.FormaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao")
                        .HasMaxLength(500);

                    b.Property<string>("Nome")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("FormaPagamento");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Forma de pagamento é Boleto",
                            Nome = "Boleto"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Forma de pagamento é Cartão de Crédito",
                            Nome = "Cartão de Crédito"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Forma de pagamento é Depósito",
                            Nome = "Depósito"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Forma de pagamento é Pix",
                            Nome = "Pix"
                        });
                });

            modelBuilder.Entity("DJERICMAX_App.Dominio.Entidades.Evento", b =>
                {
                    b.HasOne("DJERICMAX_App.Dominio.Entidades.Cliente", "Cliente")
                        .WithMany("Eventos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DJERICMAX_App.Dominio.ObjetoDeValor.FormaPagamento", "FormaPagamento")
                        .WithMany()
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DJERICMAX_App.Dominio.Entidades.ItemPedido", b =>
                {
                    b.HasOne("DJERICMAX_App.Dominio.Entidades.Evento", "Evento")
                        .WithMany("ItensPedido")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DJERICMAX_App.Dominio.Entidades.Pedido")
                        .WithMany("ItensPedido")
                        .HasForeignKey("PedidoId");

                    b.HasOne("DJERICMAX_App.Dominio.Entidades.Servico", "Servico")
                        .WithMany("ItensPedido")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DJERICMAX_App.Dominio.Entidades.Pedido", b =>
                {
                    b.HasOne("DJERICMAX_App.Dominio.Entidades.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DJERICMAX_App.Dominio.ObjetoDeValor.FormaPagamento", "FormaPagamento")
                        .WithMany()
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DJERICMAX_App.Dominio.Entidades.Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId");
                });
#pragma warning restore 612, 618
        }
    }
}
